/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CrontabIndexRouteImport } from './routes/crontab/index'
import { Route as CrontabNewRouteImport } from './routes/crontab/new'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrontabIndexRoute = CrontabIndexRouteImport.update({
  id: '/crontab/',
  path: '/crontab/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrontabNewRoute = CrontabNewRouteImport.update({
  id: '/crontab/new',
  path: '/crontab/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/chat': typeof ApiChatRoute
  '/crontab/new': typeof CrontabNewRoute
  '/crontab/': typeof CrontabIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/chat': typeof ApiChatRoute
  '/crontab/new': typeof CrontabNewRoute
  '/crontab': typeof CrontabIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/chat': typeof ApiChatRoute
  '/crontab/new': typeof CrontabNewRoute
  '/crontab/': typeof CrontabIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/api/chat' | '/crontab/new' | '/crontab/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/api/chat' | '/crontab/new' | '/crontab'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/api/chat'
    | '/crontab/new'
    | '/crontab/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ApiChatRoute: typeof ApiChatRoute
  CrontabNewRoute: typeof CrontabNewRoute
  CrontabIndexRoute: typeof CrontabIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crontab/': {
      id: '/crontab/'
      path: '/crontab'
      fullPath: '/crontab/'
      preLoaderRoute: typeof CrontabIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crontab/new': {
      id: '/crontab/new'
      path: '/crontab/new'
      fullPath: '/crontab/new'
      preLoaderRoute: typeof CrontabNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ApiChatRoute: ApiChatRoute,
  CrontabNewRoute: CrontabNewRoute,
  CrontabIndexRoute: CrontabIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
